version: "3"
   
services:
  # db:
  #   image: postgres:13
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=1q2w3e4r
    # volumes:
    #     - ./data/database:/var/lib/postgresql/data
  db:
    image: postgres:13
    # restart: always
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    # command: "gunicorn sw.wsgi:application --workers ${WORKERS} --threads=${THREADS} --bind 0.0.0.0:8000"
    volumes:
      - ./code:/code
    ports:
      - "${WEB_PORT}:8000"
    depends_on:
      - db
  